version: 2
jobs:
  build:
    working_directory: ~/test-ci-code
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: install
          command: 'npm install'
      - run:
          name: validate
          command: 'npm run validate'
