storage: ./storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@lemoncode/**':
    access: $anonymous
    publish: $anonymous
  '**':
    access: $anonymous
    publish: $anonymous
    proxy: npmjs
